clientes/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from . import views

urlpatterns = [
    path('', login_required(views.ClienteHTMxTableView.as_view()), name='clientes'),
    path('cliente/<int:pk>', login_required(views.ClienteDetalhe.as_view()),
         name='cliente_detail'),
    path('cliente/', login_required(views.ClienteCreate.as_view()),
         name='cliente_create'),
    path('cliente/<int:pk>/delete',
         login_required(views.ClienteDelete.as_view()), name='cliente_delete'),
    path('lista/', login_required(views.ClienteLista.as_view()),
         name='cliente_select'),
    path('lista/<int:pk>/', login_required(views.ClienteSelect.as_view())),
    path('<int:pk>/tabela/', login_required(views.ClientePrecos.as_view()),
         name='cliente_precos'),
    path('<int:pk>/tabela/<int:sk>', login_required(views.ClienteUpdatePrecos.as_view()),
         name='cliente_update_precos'),
    path('<int:pk>/tabela/<int:sk>/delete',
         login_required(views.ClientePrecosDelete.as_view()), name='cliente_update_precos'),
]

clientes/models.py
from django.db import models

from produtos.models import Produto

ID_UNIT = (
    (1, "Unidade 01"),
    (2, "Unidade 02"),
    (3, "Unidade 03"),
)

TYPE_PERSON = (
    (0, "Pessoa Física"),
    (1, "Pessoa Jurídica"),
)

UF_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranão'),
    ('MG', 'Minas Gerais'),
    ('MS', 'Mato Grosso do Sul'),
    ('MT', 'Mato Grosso'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PE', 'Pernanbuco'),
    ('PI', 'Piauí'),
    ('PR', 'Paraná'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('RS', 'Rio Grande do Sul'),
    ('SC', 'Santa Catarina'),
    ('SE', 'Sergipe'),
    ('SP', 'São Paulo'),
    ('TO', 'Tocantins')
)


class ClienteManager(models.Manager):
    def get_queryset(self, request=None):
        qs = super().get_queryset()
        if request and 'id_filial' in request.session:
            qs = qs.filter(filial=request.session['id_filial'])
        return qs


class Cliente(models.Model):
    filial = models.SmallIntegerField(choices=ID_UNIT, blank=True)
    nome = models.CharField(max_length=200, verbose_name="Cliente")
    razaosocial = models.CharField(
        max_length=200, blank=True, verbose_name="Razão Social")
    tipo = models.SmallIntegerField(choices=TYPE_PERSON)
    cpfcnpj = models.CharField(max_length=18, verbose_name="CPF/CNPJ")
    rgie = models.CharField(max_length=14, blank=True,
                            null=True, verbose_name="Insc.Estadual")
    endereco = models.CharField(max_length=200)
    bairro = models.CharField(max_length=150, blank=True, null=True)
    numero = models.CharField(max_length=6, blank=True, null=True)
    complemento = models.CharField(max_length=50, blank=True, null=True)
    cep = models.CharField(max_length=9, blank=True,
                           null=True, verbose_name="CEP")
    cidade = models.CharField(max_length=250, default='Belo Horizonte')
    uf = models.CharField(max_length=2, default='MG',
                          choices=UF_CHOICES, verbose_name="UF")
    email = models.EmailField(blank=True, verbose_name="E-mail")
    phone1 = models.CharField(max_length=15, verbose_name="Telefone")
    phone2 = models.CharField(
        max_length=15, blank=True, verbose_name="Telefone")
    obs = models.TextField(blank=True, verbose_name="Observações")
    delivery = models.BooleanField(default=False, verbose_name="Delivery")
    data_criacao = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('nome',)

    def __str__(self):
        return self.nome

    @property
    def nomeCliente(self):
        tmp = self.nome.strip()
        if self.delivery:
            tmp = tmp + " ( Delivery )"
        return tmp


class ClienteTabela(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    preco = models.DecimalField(
        max_digits=10, decimal_places=2, verbose_name='Preço')

    def __str__(self):
        return self.produto.nome + " " + str(self.preco)

    def datacsv(self):
        return str(self.id) + ";" + self.cliente.nome + ";" + self.produto.nome + ";" + str(self.preco)

    class Meta:
        verbose_name = "tabela"

clientes/templates/clientes/cliente_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3>Confirma exclusão permanente do Cliente:</h3><br>
            </div>        
        </div>
        <div class="row">   
            <div class="col-md-6 col-md-offset-3">           
                <form method="POST">     
                    {% csrf_token %}                 
                    <br>Cliente: {{cliente.nome}}</br>
                    <br>Razão Social: {{cliente.razaosocial}}</br>  
                    <br>CPF/CNPJ: {{cliente.cpfcnpj}}</br>    
                    <br>                
                    <input type="reset" class="btn btn-secondary" value="Cancelar" onclick="location.href='{{ request.META.HTTP_REFERER }}'">
                    <input type="submit" class="btn btn-danger" value="Apagar">
                </form>   
            </div> 
        </div>
    </div>
{% endblock %}

clientes/templates/clientes/cliente_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block titulo %}
  Cadastro de Cliente
{% endblock %}

{% block content %}
  <form method="POST" action="">
    {% csrf_token %}
    {% include 'snippets/show_messages.html' %}
    {% crispy form %}
  </form>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
  <script>
    var SPMaskBehavior = function (val) {
        return val.replace(/\D/g, '').length === 11 ? '(00) 00000-0000' : '(00) 0000-00009'
      },
      spOptions = {
        onKeyPress: function (val, e, field, options) {
          field.mask(SPMaskBehavior.apply({}, arguments), options)
        }
      }
    
    var options = {
      onKeyPress: function (cpf, ev, el, op) {
        var masks = ['000.000.000-000', '00.000.000/0000-00']
        $('.mask_cpfcnpj').mask(cpf.length > 14 ? masks[1] : masks[0], op)
      }
    }
    
    $(function () {
      $('.mask_telefone').mask(SPMaskBehavior, spOptions)
      $('.mask_cep').mask('00000-000')
      $('.mask_cpfcnpj').length > 11 ? $('.mask_cpfcnpj').mask('00.000.000/0000-00', options) : $('.mask_cpfcnpj').mask('000.000.000-00#', options)
      $('.mask_money').mask('###0,00', { reverse: true })
      /* $(".mask_money").inputmask('Regex', {regex: "^[0-9]{1,6}(\\,\\d{1,2})?$"}); */
    })
  </script>
{% endblock %}

clientes/templates/clientes/cliente_form2.html
<form  method="post" > <input type="hidden" name="csrfmiddlewaretoken" value="BoEY7TDhZ2HbH6IUgGxbnjDdwThgB5CmIeujrgqYFR529zqtymJFohnOK46YS3XU"> <div class="form-group"> <div id="div_id_delivery" class="custom-control custom-checkbox"> <input type="checkbox" name="delivery" class="checkboxinput custom-control-input" id="id_delivery"> <label for="id_delivery" class="custom-control-label">
    Delivery
</label> </div> </div> <div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_nome" class="form-group"> <label for="id_nome" class=" requiredField">
Cliente<span class="asteriskField">*</span> </label> <div> <input type="text" name="nome" maxlength="200" style="max-width: 30em" class="textinput textInput form-control" required id="id_nome"> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_razaosocial" class="form-group"> <label for="id_razaosocial" class="">
Razão Social
</label> <div> <input type="text" name="razaosocial" maxlength="200" style="max-width: 30em" class="textinput textInput form-control" id="id_razaosocial"> </div> </div> </div> </div>
<div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_tipo" class="form-group"> <label for="id_tipo" class=" requiredField">
Tipo<span class="asteriskField">*</span> </label> <div> <select name="tipo" style="max-width: 15em" class="select custom-select" required id="id_tipo"> <option value="">---------</option> <option value="0">Pessoa Física</option> <option value="1" selected>Pessoa Jurídica</option>

</select> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_cpfcnpj" class="form-group"> <label for="id_cpfcnpj" class=" requiredField">
CPF/CNPJ<span class="asteriskField">*</span> </label> <div> <input type="text" name="cpfcnpj" maxlength="18" class="mask_cpfcnpj textinput textInput form-control" style="max-width: 20em" required id="id_cpfcnpj"> </div> </div> </div> </div>
<div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_endereco" class="form-group"> <label for="id_endereco" class=" requiredField">
Endereco<span class="asteriskField">*</span> </label> <div> <input type="text" name="endereco" maxlength="200" style="max-width: 30em" class="textinput textInput form-control" required id="id_endereco"> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_bairro" class="form-group"> <label for="id_bairro" class="">
Bairro
</label> <div> <input type="text" name="bairro" maxlength="150" style="max-width: 30em" class="textinput textInput form-control" id="id_bairro"> </div> </div> </div> </div>
<div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_complemento" class="form-group"> <label for="id_complemento" class="">
Complemento
</label> <div> <input type="text" name="complemento" maxlength="50" style="max-width: 30em" class="textinput textInput form-control" id="id_complemento"> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_numero" class="form-group"> <label for="id_numero" class="">
Numero
</label> <div> <input type="text" name="numero" maxlength="6" style="max-width: 8em" class="textinput textInput form-control" id="id_numero"> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_cep" class="form-group"> <label for="id_cep" class="">
CEP
</label> <div> <input type="text" name="cep" maxlength="9" class="mask_cep textinput textInput form-control" style="max-width: 8em" id="id_cep"> </div> </div> </div> </div>
<div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_uf" class="form-group"> <label for="id_uf" class=" requiredField">
UF<span class="asteriskField">*</span> </label> <div> <select name="uf" style="max-width: 15em" class="select custom-select" id="id_uf"> <option value="AC">Acre</option> <option value="AL">Alagoas</option> <option value="AP">Amapá</option> <option value="BA">Bahia</option> <option value="CE">Ceará</option> <option value="DF">Distrito Federal</option> <option value="ES">Espírito Santo</option> <option value="GO">Goiás</option> <option value="MA">Maranão</option> <option value="MG" selected>Minas Gerais</option> <option value="MS">Mato Grosso do Sul</option> <option value="MT">Mato Grosso</option> <option value="PA">Pará</option> <option value="PB">Paraíba</option> <option value="PE">Pernanbuco</option> <option value="PI">Piauí</option> <option value="PR">Paraná</option> <option value="RJ">Rio de Janeiro</option> <option value="RN">Rio Grande do Norte</option> <option value="RO">Rondônia</option> <option value="RR">Roraima</option> <option value="RS">Rio Grande do Sul</option> <option value="SC">Santa Catarina</option> <option value="SE">Sergipe</option> <option value="SP">São Paulo</option> <option value="TO">Tocantins</option>

</select> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_cidade" class="form-group"> <label for="id_cidade" class=" requiredField">
Cidade<span class="asteriskField">*</span> </label> <div> <input type="text" name="cidade" value="Belo Horizonte" maxlength="250" style="max-width: 30em" class="textinput textInput form-control" required id="id_cidade"> </div> </div> </div> </div> <div id="div_id_email" class="form-group"> <label for="id_email" class="">
E-mail
</label> <div> <input type="email" name="email" maxlength="254" style="max-width: 30em" class="emailinput form-control" id="id_email"> </div> </div> <div  class="form-row justify-content-start" > <div 
class="form-group col-md-3 mb-0" > <div id="div_id_phone1" class="form-group"> <label for="id_phone1" class=" requiredField">
Telefone<span class="asteriskField">*</span> </label> <div> <input type="text" name="phone1" maxlength="15" class="mask_telefone textinput textInput form-control" style="max-width: 15em" required id="id_phone1"> </div> </div> </div> <div 
class="form-group col-md-3 mb-0" > <div id="div_id_phone2" class="form-group"> <label for="id_phone2" class="">
Telefone
</label> <div> <input type="text" name="phone2" maxlength="15" class="mask_telefone textinput textInput form-control" style="max-width: 15em" id="id_phone2"> </div> </div> </div> </div> </form>

<input type="reset" name="cancelar" value="Cancelar" class="btn btn-inverse"  id="reset-id-cancelar" onclick="history.go(-1);"/> 
<input type="submit" name="submit" value="Salvar" class="btn btn-primary" id="submit-id-submit" />     
</form>

clientes/templates/clientes/cliente_tabela.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load myfilters %}
{% load static %}
{% load heroicons %}

{% block content %}
  <div class="card w-full bg-base-100 shadow-xl card-bordered card-compact border border-gray-900">
    <div class="card-body">
      <h3 class="card-title">Cliente: {{ cliente }}</h3>
    </div>
  </div>

  <form method="POST" action="">
    {% csrf_token %}
    {% include 'snippets/show_messages.html' %}
    {% crispy form %}
  </form>
  <br />
  <table class="table table-hover table-sm w-75">
    <thead class="thead-light">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Produto</th>
        <th scope="col">Preço</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for item in PrecoCliente %}
        <tr onclick="document.location.href='{{ item.id }}'">
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{ item.produto }}</td>
          <td>{{ item.preco|formata_preco }}</td>
          <td>
            <a class="btn" style="color:red" href="{{ item.id }}/delete">{% heroicon_outline 'trash' %}</a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

clientes/templates/clientes/cliente_table.html
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% block titulo %}Clientes{% endblock %}
<script src="https://unpkg.com/htmx.org@1.8.4"></script>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <center><h3>Clientes</h3> </center>
                {% include 'snippets/show_messages.html' %}
            </div>
        </div>    
        <div class="row">
            <div class="col-6">                
                {# Search form #}
                <form hx-get="{% url 'clientes' %}" 
                      hx-target="div.table-container" 
                      hx-swap="outerHTML"                     
                      class="form-inline">
                    {% crispy filter.form %}
                </form>
            </div>
            <div class="col-6">                
                <button class="btn btn-primary shadow p-2 rounded" onclick="location.href='{% url 'cliente_create' %}'">Cadastrar novo</button>
            </div>
        </div>
    </div>
        
    {# The actual table #}
    {% render_table table %}
{% endblock %}

clientes/templates/clientes/cliente_table_lista.html
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load crispy_forms_tags %}
{% block titulo %}Clientes{% endblock %}
<script src="https://unpkg.com/htmx.org@1.8.4"></script>
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <center><h3>{{ txtHeader }}</h3> </center>
                {% include 'snippets/show_messages.html' %}
            </div>
        </div>    
        <div class="row">
            <div class="col-6">                
                {# Search form #}
                <form hx-get="{% url 'venda' %}" 
                      hx-target="div.table-container" 
                      hx-swap="outerHTML"                     
                      class="form-inline">
                    {% crispy filter.form %}
                </form>
            </div>
        </div>
    </div>
        
    {# The actual table #}
    {% render_table table %}
{% endblock %}

clientes/templates/clientes/cliente_table_lista_partial.html
{% load render_table from django_tables2 %}

{% block content %}

{% render_table table %}

{% endblock %}

clientes/templates/clientes/cliente_table_partial.html
{% load render_table from django_tables2 %}

{% block content %}
  {% render_table table %}
{% endblock %}

clientes/templates/clientes/clienteprecos_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <h3>Confirma exclusão permanente do item:</h3><br>
            </div>        
        </div>
        <div class="row">   
            <div class="col-md-6 col-md-offset-3">           
                <form method="POST">     
                    {% csrf_token %}                 
                    <br>Cliente: {{clientetabela.cliente}}</br>
                    <br>Produto: {{clientetabela.produto}}</br>  
                    <br>Preço: {{clientetabela.preco}}</br>   
                    <br>                
                    <input type="reset" class="btn btn-secondary" value="Cancelar" onclick="location.href='{{ request.META.HTTP_REFERER }}'">
                    <input type="submit" class="btn btn-danger" value="Apagar">
                </form>   
            </div> 
        </div>
    </div>
{% endblock %}

clientes/templates/clientes/tables.html
{% load django_tables2 %}
{% load i18n %}
<script src="https://unpkg.com/htmx.org@1.8.4"></script>
{% block table-wrapper %}
    <div id="table-container" class="table-container table-responsive">
        {% block table %}
            <table id="table" {% render_attrs table.attrs class="table" %}>
                {% block table.thead %}
                    {% if table.show_header %}
                        <thead {{ table.attrs.thead.as_html }}>
                        <tr>
                            {% for column in table.columns %}
                                <th {{ column.attrs.th.as_html }} hx-get="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}" hx-trigger="click" hx-target="#table-container" hx-swap="outerHTML" role="button">
{#                                    {% if column.orderable %}#}
{#                                        <a href="{% querystring table.prefixed_order_by_field=column.order_by_alias.next %}">{{ column.header }}</a>#}
{#                                    {% else %}#}
                                        {{ column.header }}
{#                                    {% endif %}#}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                {% endblock table.thead %}
                {% block table.tbody %}
                    <tbody id="body-target" {{ table.attrs.tbody.as_html }}>
                    {% for row in table.paginated_rows %}
                        {% block table.tbody.row %}
                            <tr {{ row.attrs.as_html }}>
                                {% for column, cell in row.items %}
                                    <td {{ column.attrs.td.as_html }}>{% if column.localize == None %}{{ cell }}{% else %}{% if column.localize %}{{ cell|localize }}{% else %}{{ cell|unlocalize }}{% endif %}{% endif %}</td>
                                {% endfor %}
                            </tr>
                        {% endblock table.tbody.row %}
                    {% empty %}
                        {% if table.empty_text %}
                            {% block table.tbody.empty_text %}
                                <tr><td colspan="{{ table.columns|length }}">{{ table.empty_text }}</td></tr>
                            {% endblock table.tbody.empty_text %}
                        {% endif %}
                    {% endfor %}
                    </tbody>
                {% endblock table.tbody %}
                {% block table.tfoot %}
                    {% if table.has_footer %}
                        <tfoot {{ table.attrs.tfoot.as_html }}>
                        <tr>
                            {% for column in table.columns %}
                                <td {{ column.attrs.tf.as_html }}>{{ column.footer }}</td>
                            {% endfor %}
                        </tr>
                        </tfoot>
                    {% endif %}
                {% endblock table.tfoot %}
            </table>
        {% endblock table %}

        {% block pagination %}
            {% if table.page and table.paginator.num_pages > 1 %}
                <nav aria-label="Table navigation">
                    <ul class="pagination justify-content-start">
                        {% if table.page.has_previous %}
                            {% block pagination.previous %}
                                <li class="previous page-item" role="button">
                                    <div hx-get="{% querystring table.prefixed_page_field=table.page.previous_page_number %}" hx-trigger="click" hx-target="#table-container" hx-swap="outerHTML" class="page-link">
                                        <span aria-hidden="true">&laquo;</span>
                                        {% trans 'previous' %}
                                    </div>
                                </li>
                            {% endblock pagination.previous %}
                        {% endif %}
                        {% if table.page.has_previous or table.page.has_next %}
                            {% block pagination.range %}
                                {% for p in table.page|table_page_range:table.paginator %}
                                    <li class="page-item{% if table.page.number == p %} active{% endif %}" role="button">
                                        <div class="page-link" {% if p != '...' %}hx-get="{% querystring table.prefixed_page_field=p %}"{% endif %} hx-trigger="click" hx-target="#table-container" hx-swap="outerHTML">
                                            {{ p }}
                                        </div>
                                    </li>
                                {% endfor %}
                            {% endblock pagination.range %}
                        {% endif %}
                        {% if table.page.has_next %}
                            {% block pagination.next %}
                                <li class="next page-item user-select" role="button">
                                    <div hx-get="{% querystring table.prefixed_page_field=table.page.next_page_number %}" hx-trigger="click" hx-target="#table-container" hx-swap="outerHTML" class="page-link">
                                        {% trans 'next' %}                                       
                                        <span aria-hidden="true">&raquo;</span>
                                    </div>
                                </li>
                            {% endblock pagination.next %}
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
        {% endblock pagination %}
    </div>
{% endblock table-wrapper %}